Resources:
  RedirectorCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - ${self:provider.domain}
        ViewerCertificate:
          AcmCertificateArn: ${self:provider.cert}
          MinimumProtocolVersion: "TLSv1.2_2019"
          SslSupportMethod: sni-only
        Origins:
          - Id: "OriginServer"
            DomainName: ${self:provider.origin}
            OriginPath: /${self:provider.stage}
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - "TLSv1.2"
        DefaultCacheBehavior:
          AllowedMethods:
            - "GET"
            - "HEAD"
            - "OPTIONS"
            - "PUT"
            - "POST"
            - "PATCH"
            - "DELETE"
          CachePolicyId: !Ref CachePolicy
          TargetOriginId:  "OriginServer"
          ViewerProtocolPolicy: "redirect-to-https"
        Enabled: "true"
        HttpVersion: http2
        IPV6Enabled: "false"

  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: "CachingDisabled"
        Comment: "no caching policy"
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: "false"
          EnableAcceptEncodingGzip: "false"
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

