Description: Cloudfront distribution for custom origin
Parameters:
  Alias:
    Description: DNS name of your origin
    Type: String
    Default: "api.maslick.ru"
  Certificate:
    Description: SSL certificate ARN
    Type: String
    Default: "arn:aws:acm:us-east-1:xxxxxxxxx:certificate/d544237c-xxxx-yyyy-9e92-183d99899"
  Origin:
    Description: Origin domain name (where to forward requests)
    Type: String
    Default: ""
  Path:
    Description: Origin path (e.g. /dev)
    Type: String
    Default: ""

Resources:
  RedirectorCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Alias
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: "TLSv1.2_2019"
          SslSupportMethod: sni-only
        Origins:
          - Id: "OriginServer"
            DomainName: !Ref Origin
            OriginPath: !Ref Path
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - "TLSv1.2"
        DefaultCacheBehavior:
          AllowedMethods:
            - "GET"
            - "HEAD"
            - "OPTIONS"
            - "PUT"
            - "POST"
            - "PATCH"
            - "DELETE"
          CachePolicyId: !Ref CachePolicy
          TargetOriginId:  "OriginServer"
          ViewerProtocolPolicy: "redirect-to-https"
        Enabled: "true"
        HttpVersion: http2
        IPV6Enabled: "false"

  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub CachingDisabled-${AWS::StackName}
        Comment: "no caching policy"
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: "false"
          EnableAcceptEncodingGzip: "false"
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

Outputs:
  CDN:
    Description: A reference to Cloudfront distribution
    Value: !Ref RedirectorCDN
